- name: Hostname
  hostname: name={{ hostname }}
  when: not ansible_virtualization_type == "lxc"

- name: Timezone
  timezone: name=Europe/Moscow

- name: Utilites
  dnf:
    name: ['man', 'vim', 'less', 'tree', 'bash-completion'] state=latest

- name: SSH
  block:
    - yum: name=openssh-server state=latest
    - service: name=sshd enabled=yes state=started
    - lineinfile: dest=/etc/ssh/sshd_config line='UseDNS no'

- block:
  - name: GNOME DE
    yum:
      state: latest
      name:
        # XORG
        - "@base-x"
        # DISPLAY AND WINDOW MANAGER
        #- gnome-session-wayland-session
        - gnome-session-xsession
        - control-center
        - krb5-libs
        - gnome-tweak-tool
        - dconf-editor
        - centos-logos
        #F- dmz-cursor-themes
        # MOUNT AND FILE MANAGER
        - gvfs-mtp
        - gvfs-smb
        - gvfs-fuse
        - file-roller-nautilus
        #F- gvfs-archive
        # UTILITES
        - seahorse
        - gnome-terminal
        - gnome-screenshot
        # INTERNET
        - firefox
        # OFFICE
        - eog
        - gedit
        - evince

  - name: SYSTEMD TARGET
    block:
      - command: systemctl get-default
        register: contents
      - command: systemctl set-default graphical.target
        when: contents.stdout != "graphical.target"

  - name: FONTS
    block:
      - copy: src=fonts/ dest=/usr/share/fonts/
        register: fonts
      - command: fc-cache -f /usr/share/fonts/
        when: fonts.changed
      - copy: src=03-fonts-settings dest=/etc/dconf/db/local.d/03-fonts-settings
        notify:
          - dconf_update

  - name: VNC SERVER
    copy: src=04-vino-settings dest=/etc/dconf/db/local.d/04-vino-settings
    notify:
      - dconf_update

  tags: [ never, gnome_de ]
