- block:
    - name: Hostname
      hostname: name={{ hostname }}
      notify:
        - nm_restart
    
    - name: terminal utilites
      yum:
        state: latest
        name:
          - man
          - bash-completion
          - tmux
          - vim
          - less
          - atop

    - name: file utilites
      yum:
        state: latest
        name:
          - ncdu
          - tree
          - mc
          - unzip
          - p7zip
          - p7zip-plugins
          - cifs-utils
          - lsof
          - iotop
          - sysstat

    - name: network utilites
      yum:
        state: latest
        name:
          - bind-utils
          - curl
          - arp-scan
          - iftop
          - nload
          - nmap
          - iperf3
    
    - name: SSH 1
      yum: name=openssh-server state=latest
    
    - name: SSH 2
      service: name=sshd enabled=yes state=started
    
    - name: Time sync 1
      yum: name=chrony state=latest
    
    - name: Time sync 2
      service: name=chronyd enabled=yes state=started

    - name: Power-profiles 1
      yum: name=power-profiles-daemon state=latest

    - name: Power-profiles 2
      service: name=power-profiles-daemon enabled=yes state=started

  become: true
