- name: "Added EPEL"
  ansible.builtin.include_tasks: repos/epel.yml

- name: "Basic setup"
  become: true
  block:
    - name: "Setup hostname"
      ansible.builtin.hostname:
        name: "{{ hostname }}"

    - name: "Add common utilites"
      ansible.builtin.yum:
        state: present
        name:
          - man
          - vim
          - less
          - atop
          - lshw

  # - name: "Add power-profiles daemon"
  #   ansible.builtin.yum:
  #     name: power-profiles-daemon
  #     state: present
  # - name: "Enable power-profiles daemon"
  #   ansible.builtin.service:
  #     name: power-profiles-daemon
  #     enabled: true
  #     state: started

    - name: "Enable fstrim timer"
      ansible.builtin.systemd:
        name: fstrim.timer
        enabled: true
