- block:
    - name: Hostname
      hostname: name={{ hostname }}
      notify:
        - nm_restart
    
    - name: Utilites
      yum:
        state: latest
        name:
          - ncdu
          - tree
          - mc
          - unzip
          - p7zip
          - p7zip-plugins
          - cifs-utils
          - lsof
          - bind-utils
          - curl
          - man
          - bash-completion
          - tmux
          - vim
          - less
    
    - name: SSH 1
      yum: name=openssh-server state=latest
    
    - name: SSH 2
      service: name=sshd enabled=yes state=started
    
    - name: Time sync 1
      yum: name=chrony state=latest
    
    - name: Time sync 2
      service: name=chronyd enabled=yes state=started

  become: true
