
- block:
    - name: hostname
      hostname: name={{ hostname }}
    
    - name: common oracle epel repo
      yum: name=oracle-epel-release-el9 state=latest
      when: ansible_distribution == "OracleLinux" and ansible_distribution_major_version == "9"

    - name: common utilites
      yum:
        state: latest
        name:
          - man
          - bash-completion
          - tmux
          - vim
          - less
          - atop
          - lshw

    - name: file utilites
      yum:
        state: latest
        name:
          - ncdu
          - tree
          - mc
          - unzip
          - p7zip
          - p7zip-plugins
          - tar
          - zstd
          - cifs-utils
          - lsof
          - iotop
          - sysstat

    - name: network utilites
      yum:
        state: latest
        name:
          - bind-utils
          - curl
          - arp-scan
          - iftop
          - nload
          - nmap
          - iperf3
          - traceroute
    
    - name: SSH 1
      yum: name=openssh-server state=latest
    
    - name: SSH 2
      service: name=sshd enabled=yes state=started
    
    - name: time sync 1
      yum: name=chrony state=latest
    
    - name: time sync 2
      service: name=chronyd enabled=yes state=started

    - name: power-profiles 1
      yum: name=power-profiles-daemon state=latest

    - name: power-profiles 2
      service: name=power-profiles-daemon enabled=yes state=started

    - name: fstrim timer
      systemd: name=fstrim.timer enabled=yes

  become: true
