- name: "Added EPEL"
  ansible.builtin.include_tasks: repos/epel.yml

- name: "Basic setup"
  become: true
  block:
    - name: "Setup hostname"
      ansible.builtin.hostname:
        name: "{{ hostname }}"

    - name: "Add common utilites"
      ansible.builtin.yum:
        state: present
        name:
          - man
          - bash-completion
          - tmux
          - vim
          - less
          - atop
          - lshw

    - name: "Add file utilites"
      ansible.builtin.yum:
        state: present
        name:
          - ncdu
          - tree
          - mc
          - unzip
          - p7zip
          - p7zip-plugins
          - tar
          - zstd
          - cifs-utils
          - lsof
          - iotop
          - sysstat

    - name: "Add network utilites"
      ansible.builtin.yum:
        state: present
        name:
          - bind-utils
          - curl
          - arp-scan
          - iftop
          - nload
          - nmap
          - iperf3
          - traceroute

    - name: "Add SSH server"
      ansible.builtin.yum:
        name: openssh-server
        state: present
    - name: "Enable SSH server"
      ansible.builtin.service:
        name: sshd
        enabled: true
        state: started

    - name: "Add Chrony"
      ansible.builtin.yum:
        name: chrony
        state: present
    - name: "Enable Chrony"
      ansible.builtin.service:
        name: chronyd
        enabled: true
        state: started

    - name: "Add power-profiles daemon"
      ansible.builtin.yum:
        name: power-profiles-daemon
        state: present
    - name: "Enable power-profiles daemon"
      ansible.builtin.service:
        name: power-profiles-daemon
        enabled: true
        state: started

    - name: "Enable fstrim timer"
      ansible.builtin.systemd:
        name: fstrim.timer
        enabled: true
