---
- name: "Check extension {{ extension_name }}"
  ansible.builtin.command: gnome-extensions show {{ extension_name }}
  register: contents
  changed_when: false

- name: "Enable extension {{ extension_name }}"
  ansible.builtin.command: gnome-extensions enable {{ extension_name }}
  when: "'State: ENABLED' not in contents.stdout"
