#-----------------------------------------------------------------------------------------------
# GNOME
- name: gnome packages
  yum:
    state: latest
    name:
      - "@base-x"
      - gnome-session-xsession
      - control-center
      - krb5-libs
      - gnome-tweak-tool
      - dconf-editor
      - python3-psutil
      - dbus-x11
  notify:
    - nm_restart
  become: true

- name: gnome extensions
  import_role:
    name: jaredhocutt.gnome_extensions
  vars:
    gnome_extension_ids:
      - 21
      - 1287
      - 1411
      - 2087
  notify:
    - enable_extensions

#-----------------------------------------------------------------------------------------------
# GNOME START_UP SETUP
- name: systemd target 1
  command: systemctl get-default
  register: contents
  changed_when: false
  become: true

- name: systemd target 2
  command: systemctl set-default graphical.target
  when: contents.stdout != "graphical.target"
  become: true

- name: gdm wayland disable
  lineinfile:
    path: /etc/gdm/custom.conf
    regexp: 'WaylandEnable='
    line: WaylandEnable=false
  become: true

#- name: gnome disable welcome dialog
#  dconf: key="/org/gnome/shell/welcome-dialog-last-shown-version" value="40.0"

#-----------------------------------------------------------------------------------------------
# GNOME START-UP
- name: gnome autologin
  blockinfile:
    dest: /etc/gdm/custom.conf
    marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK gnome autologin -->"
    insertafter: "\\[daemon\\]"
    block: |
      AutomaticLoginEnable=True
      AutomaticLogin={{ ansible_user_id }}
  become: true

- name: systemd isolate graphical
  command: systemctl isolate graphical.target
  become: true

- name: Wait for graphical target loading
  pause:
    seconds: 30

- name: gnome autologin
  blockinfile:
    dest: /etc/gdm/custom.conf
    marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK gnome autologin -->"
    state: absent
  become: true

#-----------------------------------------------------------------------------------------------
# GNOME EXTENSIONS
- name: gnome unite 1
  yum: name=xprop state=latest
  become: true

- name: gnome unite 2
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value |string }}"
  loop:
    - { key: "/org/gnome/shell/extensions/unite/extend-left-box", value: "false" }
    - { key: "/org/gnome/shell/extensions/unite/show-desktop-name", value: "false" }
    - { key: "/org/gnome/shell/extensions/unite/hide-app-menu-icon", value: "true" }
    - { key: "/org/gnome/shell/extensions/unite/hide-app-menu-arrow", value: "true" }
    - { key: "/org/gnome/shell/extensions/unite/greyscale-tray-icons", value: "true" }
    - { key: "/org/gnome/shell/extensions/unite/window-buttons-theme", value: "'united-dark'" }
    - { key: "/org/gnome/shell/extensions/unite/hide-activities-button", value: "'never'" }
    - { key: "/org/gnome/shell/extensions/unite/window-buttons-placement", value: "'last'" }
    - { key: "/org/gnome/shell/extensions/unite/hide-aggregate-menu-arrow", value: "true" }

- name: gnome workspace 1
  dconf: key="/org/gnome/mutter/dynamic-workspaces" value="false"

- name: gnome workspace 2
  dconf: key="/org/gnome/shell/overrides/dynamic-workspaces" value="false"

#-----------------------------------------------------------------------------------------------
# GNOME APPEARANCE
- name: gtk theme 1
  file: path=~/.config/gtk-3.0/ state=directory

- name: gtk theme 2
  blockinfile:
    dest: ~/.config/gtk-3.0/settings.ini
    create: yes
    marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK gtk theme 2 -->"
    block: |
      [Settings]
      gtk-application-prefer-dark-theme=1

- name: gnome fonts 1
  file:
    path: ~/.local/share/fonts/
    state: directory

- name: gnome fonts 2
  unarchive:
    src: http://ftp.gnome.org/pub/GNOME/sources/ttf-bitstream-vera/1.10/ttf-bitstream-vera-1.10.zip
    dest: ~/.local/share/fonts/
    remote_src: yes
    creates: ~/.local/share/fonts/ttf-bitstream-vera-1.10/
  register: fonts_state

- name: gnome fonts 3
  unarchive:
    src: https://assets.ubuntu.com/v1/0cef8205-ubuntu-font-family-0.83.zip
    dest: ~/.local/share/fonts/
    remote_src: yes
    creates: ~/.local/share/fonts/ubuntu-font-family-0.83/
  register: fonts_state

- name: gnome fonts 3
  command: fc-cache -f ~/.local/share/fonts/
  when: fonts_state.changed

- name: gnome fonts 4
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value |string }}"
  loop:
    - { key: "/org/gnome/desktop/interface/monospace-font-name", value: "'Bitstream Vera Sans Mono 11'" }
    - { key: "/org/gnome/desktop/interface/font-name", value: "'Ubuntu 11'" }
    - { key: "/org/gnome/desktop/wm/preferences/titlebar-uses-system-font", value: "true" }
    - { key: "/org/gnome/desktop/wm/preferences/titlebar-font", value: "'Ubuntu Medium 11'" }

- name: gnome background and screensaver
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value |string }}"
  loop:
    - { key: "/org/gnome/desktop/background/picture-uri", value: "'file:////usr/share/gnome-control-center/pixmaps/noise-texture-light.png'" }
    - { key: "/org/gnome/desktop/background/primary-color", value: "'#2e3436'" }
    - { key: "/org/gnome/desktop/background/picture-options", value: "'wallpaper'" }
    - { key: "/org/gnome/desktop/screensaver/picture-uri", value: "'file:////usr/share/gnome-control-center/pixmaps/noise-texture-light.png'" }
    - { key: "/org/gnome/desktop/screensaver/primary-color", value: "'#2e3436'" }
    - { key: "/org/gnome/desktop/screensaver/picture-options", value: "'wallpaper'" }

- name: gnome nightlight
  dconf: key="/org/gnome/settings-daemon/plugins/color/night-light-enabled" value="true"

- name: gnome button-layout
  dconf: key="/org/gnome/desktop/wm/preferences/button-layout" value="'appmenu:minimize,maximize,close'"

- name: gnome clock
  dconf: key="/org/gnome/desktop/interface/clock-show-weekday" value="true"

- name: gnome battery
  dconf: key="/org/gnome/desktop/interface/show-battery-percentage" value="true"

- name: gnome wm hotkeys
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value |string }}"
  loop:
    - { key: "/org/gnome/desktop/wm/keybindings/close", value: "['<Super>q']" }
    - { key: "/org/gnome/desktop/wm/keybindings/show-desktop", value: "['<Super>d']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-applications", value: "@as []" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-applications-backward", value: "@as []" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-windows", value: "['<Alt>Tab']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-1", value: "['<Primary>1']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-2", value: "['<Primary>2']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-3", value: "['<Primary>3']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-4", value: "['<Primary>4']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-1", value: "['<Primary><Shift>exclam']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-2", value: "['<Primary><Shift>at']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-3", value: "['<Primary><Shift>numbersign']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-4", value: "['<Primary><Shift>dollar']" }

- block:
    - name: gnome lock&sleep
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value |string }}"
      loop:
        - { key: "/org/gnome/desktop/lockdown/disable-lock-screen", value: "true" }
        - { key: "/org/gnome/desktop/screensaver/lock-enabled", value: "false" }
        - { key: "/org/gnome/desktop/session/idle-delay", value: "uint32 0" }
        - { key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type", value: "'nothing'" }
    
    - name: gnome monitors
      copy: src=monitors.xml dest=~/.config/

    #- name: gnome autologin
    #  blockinfile:
    #    dest: /etc/gdm/custom.conf
    #    marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK gnome autologin -->"
    #    insertafter: "\\[daemon\\]"
    #    block: |
    #      AutomaticLoginEnable=True
    #      AutomaticLogin={{ ansible_user_id }}
    #  become: true

  when: ansible_virtualization_role == "guest"
