---
#------------------------------------------------------------------------------------------
# HOSTNAME
   - name: Hostname
     block:
       - name: Setup hostname
         hostname: name={{ hostname }}
     when: not ansible_virtualization_type == "lxc"

#------------------------------------------------------------------------------------------
# LOCALIZATION
   - name: Timezone
     timezone: name=Europe/Moscow
   - name: Locale [ALWAYS CHANGED]
     command: localectl set-locale LANG=ru_RU.UTF-8 LC_MESSAGES=en_US.UTF-8
   - name: Keymap [ALWAYS CHANGED]
     command: localectl --no-convert set-keymap us,ru

#------------------------------------------------------------------------------------------
# PACKAGES
   - name: Utilites
     yum:
       state: latest
       name:
         - sudo
#
         - mc 
         - unzip
#        - p7zip
#        - p7zip-plugins
         - cifs-utils
         - tree
#         - ncdu
#
         - lsof 
         - traceroute 
         - bind-utils
         - wget
#
         - man
         - vim
         - less
         - tmux
         - bash-completion
#
         - lshw 
         - iotop
         - sysstat
         - pciutils
         - usbutils
         - lsscsi

#------------------------------------------------------------------------------------------
# SSH
   - name: SSH 1
     yum: name=openssh-server state=latest
   - name: SSH 2
     service: name=sshd enabled=yes state=started

#------------------------------------------------------------------------------------------
# AUTOUPDATE
   - name: Autoupdate
     block:
       - name: Autoupdate 1
         yum: name=epel-release state=present
       - name: Autoupdate 2
         yum: name=auter state=latest
#      - name: Enabling only security updates
#        replace: dest=/etc/auter/auter.conf regexp='PACKAGEMANAGEROPTIONS=""' replace='PACKAGEMANAGEROPTIONS="--security"'
       - name: Autoupdate 3
         replace: dest=/etc/auter/auter.conf regexp='AUTOREBOOT="no"' replace='AUTOREBOOT="yes"'
       - name: Autoupdate 4
         lineinfile: "dest=/etc/cron.d/auter line='30 2 * * *    root /usr/bin/auter --apply'"
     when: autoupdate

#------------------------------------------------------------------------------------------
# MTA 
   - name: MTA 1
     lineinfile: "dest=/etc/aliases line='root:   {{ email }}'"
   - name: MTA 2
     yum: name=postfix state=latest
