Vagrant.configure("2") do |config|

  config.vm.define "debian", autostart: true, primary: true do |debian|
    debian.vm.box = "debian/trixie64"
    debian.vm.provider :libvirt do |lv|
      lv.title = 'debian'
      lv.machine_virtual_size = 16
    end
  end

  config.vm.provider :libvirt do |lv|
    lv.cpus = 4
    lv.memory = 4096
    lv.video_type = 'virtio'
    lv.graphics_type = 'spice'
    lv.default_prefix = ''
    lv.qemu_use_session = false
  end

  config.vm.synced_folder "../ansible", "/vagrant", type: "rsync"

  config.vm.provision "deploy DE", type: "shell", privileged: false,
    inline: <<-SHELL
      set -e
      set -x
      cd /vagrant
      rm -r .venv || true
      source /etc/os-release
      case "${PRETTY_NAME}" in
      "Debian GNU/Linux 13 (trixie)")
        sudo apt -y install git python3.13-venv
        ;;
      *)
        echo "Error, unsupported os"
        exit 1
        ;;
      esac
        python3.13 -m venv --upgrade-deps .venv && source .venv/bin/activate
        python --version
      pip install --requirement pip_requirements.txt
        pip list --format freeze
        ansible-lint --version
      export ANSIBLE_CONFIG=ansible.cfg
      ansible-galaxy install --role-file galaxy_requirements.yml
        ansible-galaxy collection list --format yaml
        ansible-lint
        ansible-inventory --graph --vars
      ansible-playbook playbook.yml
      # ansible-playbook playbook.yml --tags basic
    SHELL
end
