---
dependency:
  name: galaxy
  options:
    role-file: galaxy_requirements.yml
    requirements-file: galaxy_requirements.yml

driver:
  name: vagrant
  provider:
    name: libvirt
  provision: false
  cachier: machine
  parallel: false

platforms:
  - name: alma
    hostname: alma
    box: almalinux/9
    box_url: https://app.vagrantup.com/almalinux/boxes/9/versions/9.1.20221117/providers/libvirt.box
    cpus: 4
    memory: 4096
    provider_options:
      title: 'alma'
      default_prefix: ''
      video_type: 'virtio'
      graphics_type: 'spice'
      qemu_use_session: false
  - name: fedora
    hostname: fedora
    box: fedora/39-cloud-base
    box_url: https://mirror.yandex.ru/fedora/linux/releases/39/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-39-1.5.x86_64.vagrant-libvirt.box
    cpus: 4
    memory: 4096
    provider_options:
      title: 'fedora'
      default_prefix: ''
      video_type: 'virtio'
      graphics_type: 'spice'
      qemu_use_session: false
  - name: oracle
    hostname: oracle
    box: oraclelinux/9-btrfs
    box_url: https://oracle.github.io/vagrant-projects/boxes/oraclelinux/9-btrfs.json
    cpus: 4
    memory: 4096
    provider_options:
      title: 'oracle'
      default_prefix: ''
      video_type: 'virtio'
      graphics_type: 'spice'
      qemu_use_session: false

provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: 'ansible.posix.profile_tasks'
  log: false
  env:
    ANSIBLE_VERBOSITY: 0
  playbooks:
    prepare: ../../prerun.yml
    converge: ../../run.yml

verifier:
  name: ansible

lint:
  ansible-lint
