- block: MINIMAL
  - name: Bugfixes
    block:
      - name: sg error workaround (CentOS 8 only, https://access.redhat.com/solutions/3881701)
        lineinfile: dest=/etc/dracut.conf.d/sg_fix.conf line='add_drivers+="sg"' create=yes
    when: ansible_distribution_major_version == "8"
  
  - name: Hostname
    hostname: name={{ hostname }}
    when: not ansible_virtualization_type == "lxc"
  
  - name: Timezone
    timezone: name=Europe/Moscow
  
  - name: Utilites
    yum:
      state: latest
      name:
        - ncdu
        - tree
        - mc
        - unzip
        - p7zip
        - p7zip-plugins
        - cifs-utils
        - lsof
        - bind-utils
        - curl
        - man
        - vim
        - less
        - tmux
        - bash-completion
  
  - name: SSH
    block:
      - name: SSH 1
        yum: name=openssh-server state=latest
      - name: SSH 2
        service: name=sshd enabled=yes state=started
      - name: SSH 3
        lineinfile: dest=/etc/ssh/sshd_config line='UseDNS no'
  tags: [ minimal ]
  
- block: GNOME_DE
  - name: X11 (CentOS 7 only)
    yum: name="@X Window System" state=latest
    when: ansible_distribution_major_version == "7"

  - name: X11 (CentOS 8 only)
    yum: name="@base-x" state=latest
    when: ansible_distribution_major_version == "8"

  - name: GNOME DE
    yum:
      state: latest
      name:
        # DISPLAY AND WINDOW MANAGER
        - gnome-session-xsession
        - control-center
        - krb5-libs
        - gnome-tweak-tool
        - dconf-editor
        - centos-logos
        # MOUNT AND FILE MANAGER
        - nautilus
        - gnome-terminal-nautilus
        - gvfs-mtp
        - gvfs-smb
        - gvfs-gphoto2
        - gvfs-fuse
        - file-roller-nautilus
        # UTILITES
        - seahorse
        - gnome-terminal
        - gnome-screenshot
        # INTERNET
        - firefox
        # OFFICE
        - eog
        - gedit
        - evince

  - name: SYSTEMD TARGET
    block:
      - name: SYSTEMD TARGET 1
        command: systemctl get-default
        register: contents
      - name: SYSTEMD TARGET 2
        command: systemctl set-default graphical.target
        when: contents.stdout != "graphical.target"

  - name: THEME
    block:
      - name: THEME 1
        file: path=/etc/skel/.config/gtk-3.0/ state=directory
      - name: THEME 2
        blockinfile:
          dest: /etc/skel/.config/gtk-3.0/settings.ini
          create: yes
          block: |
            [Settings]
            gtk-application-prefer-dark-theme=1
      - name: THEME 3
        copy: src=01-default-gui-settings dest=/etc/dconf/db/local.d/01-default-gui-settings
        notify:
          - dconf_update

  - name: FONTS
    block:
      - name: FONTS 1
        copy: src=fonts/ dest=/usr/share/fonts/
        register: fonts
      - name: FONTS 2
        command: fc-cache -f /usr/share/fonts/
        when: fonts.changed
      - name: FONTS 3
        copy: src=03-fonts-settings dest=/etc/dconf/db/local.d/03-fonts-settings
        notify:
          - dconf_update

  - name: VNC SERVER
    copy: src=04-vino-settings dest=/etc/dconf/db/local.d/04-vino-settings
    notify:
      - dconf_update

  tags: [ never, gnome_de ]
  when: not ansible_virtualization_type == "lxc"
