- name: Hostname
  hostname: name={{ hostname }}
  notify:
    - nm_restart
  when: not ansible_virtualization_type == "lxc"

- name: Utilites
  yum:
    state: latest
    name:
      - ncdu
      - tree
      - mc
      - unzip
      - p7zip
      - p7zip-plugins
      - cifs-utils
      - lsof
      - bind-utils
      - curl
      - man
      - vim
      - less
      - tmux
      - bash-completion

- name: SSH
  block:
    - name: SSH 1
      yum: name=openssh-server state=latest
    - name: SSH 2
      service: name=sshd enabled=yes state=restarted

- block:
  - name: X11
    block:
      - name: X11 1
        yum: name="@X Window System" state=latest
        when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7")
      - name: X11 2
        yum: name="@base-x" state=latest
        when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "8") or
              (ansible_facts['distribution'] == "Fedora" and ansible_facts['distribution_major_version'] == "31")

  - name: GNOME DE
    yum:
      state: latest
      name:
        # DISPLAY AND WINDOW MANAGER
        - gnome-session-xsession
        - control-center
        - krb5-libs
        - gnome-tweak-tool
        - dconf-editor
        # MOUNT AND FILE MANAGER
        - nautilus
        - gnome-terminal-nautilus
        - gvfs-mtp
        - gvfs-smb
        - gvfs-gphoto2
        - gvfs-fuse
        - file-roller-nautilus
        - xdg-utils
        # UTILITES
        - seahorse
        - gnome-terminal
        - gnome-screenshot
        # INTERNET
        - firefox
        # MEDIA
        - eog
        # OFFICE
        - gedit
        - evince
    notify:
      - nm_restart

  - name: SYSTEMD TARGET
    block:
      - name: SYSTEMD TARGET 1
        command: systemctl get-default
        register: contents
      - name: SYSTEMD TARGET 2
        command: systemctl set-default graphical.target
        when: contents.stdout != "graphical.target"

  - name: THEME
    block:
      - name: THEME 1
        file: path=/etc/skel/.config/gtk-3.0/ state=directory
      - name: THEME 2
        blockinfile:
          dest: /etc/skel/.config/gtk-3.0/settings.ini
          create: yes
          block: |
            [Settings]
            gtk-application-prefer-dark-theme=1
      - name: THEME 3
        copy: src=01-theme dest=/etc/dconf/db/local.d/01-theme
        notify:
          - dconf_update

  - name: FONTS
    block:
      - name: FONTS 1
        copy: src=fonts/ dest=/usr/share/fonts/
        register: fonts
      - name: FONTS 2
        command: fc-cache -f /usr/share/fonts/
        when: fonts.changed
      - name: FONTS 3
        copy: src=02-fonts dest=/etc/dconf/db/local.d/02-fonts
        notify:
          - dconf_update

  tags: [ never, gnome_de ]
  when: not ansible_virtualization_type == "lxc"
