---
- name: "Prepare system"
  hosts: all
  tasks:
    - name: "Upgrade all packages" # noqa: package-latest
      become: true
      ansible.builtin.yum:
        name: '*'
        state: latest
    - name: "Apply upgrades"
      become: true
      ansible.builtin.reboot:
