---
- name: "local host provisioning"
  hosts: localhost
  vars:
   hostname: somehostname
   email: somename@mail.box
#----------------------------------------
  roles:
    - { role: common, autoupdate: true }
    #- { role: gui }
#----------------------------------------
  tasks: 
    - name: USER
      user: name=someusername groups=wheel append=yes

#    - name: DEBUG
#      debug: msg={{ hostname }}
