- name: "Add flatpak"
  ansible.builtin.yum:
    name: flatpak
    state: present
  become: true

- name: "Add flathub repo"
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  become: true
