- name: "Add public gpg keys"
  when: ansible_distribution == "Fedora"
  ansible.builtin.dnf:
    name: distribution-gpg-keys
    state: present
  become: true

- name: "Setup RPM Fusion free repo for Fedora"
  become: true
  when: ansible_distribution == "Fedora"
  block:
    - name: "Add RPM Fusion gpg key"
      ansible.builtin.rpm_key:
        state: present
        key: "{{ item }}"
      loop:
        - /usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-free-fedora-{{ ansible_distribution_major_version }}

    - name: "Add RPM Fusion free repo for Fedora"
      ansible.builtin.dnf:
        name: https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
        state: present
