---
- name: restart NetworkManager
  service: name=NetworkManager state=restarted
  listen: "nm_restart"
  become: true

- name: gnome logout
  shell: gnome-session-quit --no-prompt
  listen: "session_logout"
