---
- name: "Workaround for Desktop Icons NG extenstion"
  ansible.builtin.shell: gnome-extensions disable ding@rastersoft.com && gnome-extensions enable ding@rastersoft.com
  changed_when: false

# - name: "Force gnome logout"
#   ansible.builtin.shell:  # noqa command-instead-of-shell
#     cmd: gnome-session-quit --no-prompt
#   listen: "restart_gui"
#   changed_when: false
#
# - name: "Update desktop database"
#   ansible.builtin.command: # noqa command-instead-of-shell
#     cmd: update-desktop-database
#   listen: "update_links"
#   changed_when: false
#   become: true
