---
- name: nm_restart
  service: name=NetworkManager state=restarted
  become: true

- name: enable gnome extensions
  shell: for i in $(gnome-extensions list); do echo $i; gnome-extensions enable $i; done
  listen: "enable_extensions"

- name: gnome logout
  shell: gnome-session-quit --no-prompt
  listen: "enable_extensions"
